# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
from datetime import datetime

print(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')}")

limit = 100
terms = {}

for i in range(2, limit + 1):
    for j in range(2, limit + 1):
        result = i**j
        terms[result] = 0

print(len(terms))
print(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')}")
